# This docker-compose application stands up the following services:
#   - a webserver on port 8080
#   - a FetchCommunicationService on port 9090
#   - a SearchService on port 9091


version: "3"

volumes:
  index_volume:

services:

  # Servers

  fetch:
    image: hltcoe/concrete-python
    command: fetch-server.py --loglevel debug /data/augmented_sources.concrete
    ports:
      - "9090:9090"
    volumes:
      - ../data:/data/

#   # If you want to use the WikiQA corpus, comment out the 'fetch' configuration
#   # section above, and uncomment the four lines below:
#   fetch:
#     image: hltcoe/fetch-wikiqa-corpus
#   ports:
#     - "9090:9090"

  search:
    depends_on:
      - fetch
    image: hltcoe/cadet-search-lucene
    command: -p 9090 -d /index_dir/ --fh fetch --fp 9090 --run-search
    ports:
      - "9091:9090"
    volumes:
      - index_volume:/index_dir

  ui:
    image: hltcoe/simple-search-demo
    command: --host 0.0.0.0 --port 8080 --fetch-host fetch --fetch-port 9090 --search-host search --search-port 9090 --lru-cache-size 50
    depends_on:
      - fetch
      - search
    ports:
      - "8080:8080"
